export enum GoogleAdminDirectoryOperationName {
  USERS_BY_ID = 'GOOGLE_ADMIN_DIRECTORY/USERS/BY_ID',
  USERS_SEARCH = 'GOOGLE_ADMIN_DIRECTORY/USERS/SEARCH',
  USERS_CREATE = 'GOOGLE_ADMIN_DIRECTORY/USERS/CREATE',
  USERS_UPDATE = 'GOOGLE_ADMIN_DIRECTORY/USERS/UPDATE',
  USERS_DELETE = 'GOOGLE_ADMIN_DIRECTORY/USERS/DELETE',
}
