export enum BreadOperationName {
  SETUP_BASIC_AUTH = 'BREAD/SETUP_BASIC_AUTH',
  EMPLOYEE_SEARCH = 'BREAD/EMPLOYEE/SEARCH',
  EMPLOYEE_BY_ID = 'BREAD/EMPLOYEE/BY_ID',
  EMPLOYEE_CREATE = 'BREAD/EMPLOYEE/CREATE',
  EMPLOYEE_UPDATE = 'BREAD/EMPLOYEE/UPDATE',
  EMPLOYEE_DELETE = 'BREAD/EMPLOYEE/DELETE',

  JOB_APPLICATION_SEARCH = 'BREAD/JOB_APPLICATION/SEARCH',

  JOB_APPLICANT_SEARCH = 'BREAD/JOB_APPLICANT/SEARCH',
}
