import type { ReactNode } from 'react';

import { Toaster } from 'saas-ui/shadcn/sonner';

import { Providers } from './Providers';
import './global.css';

export const metadata = {
  title: 'Welcome to saas-app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {children}
          <Toaster
            position={'bottom-center'}
            richColors={true}
            theme={'light'}
          />
        </Providers>
      </body>
    </html>
  );
}
