export enum GsuiteAdminOperationName {
  USERS_BY_ID = 'GSUITE_ADMIN/USERS/BY_ID',
  USERS_SEARCH = 'GSUITE_ADMIN/USERS/SEARCH',
  USERS_CREATE = 'GSUITE_ADMIN/USERS/CREATE',
  USERS_UPDATE = 'GSUITE_ADMIN/USERS/UPDATE',
  USERS_DELETE = 'GSUITE_ADMIN/USERS/DELETE'
}
