export enum GoogleContactsOperationName {
  PEOPLE_SEARCH = 'GOOGLE/PEOPLE/SEARCH',
  PEOPLE_CREATE = 'GOOGLE/PEOPLE/CREATE',
  PEOPLE_UPDATE = 'GOOGLE/PEOPLE/UPDATE',
  PEOPLE_DELETE = 'GOOGLE/PEOPLE/DELETE',
  PEOPLE_BY_ID = 'GOOGLE/PEOPLE/BY_ID',
}
