export const BAMBOO_EMPLOYEE_MOCK = {
  canUploadPhoto: 1,
  department: 'IT',
  displayName: 'Test Employee',
  division: 'web',
  firstName: 'Test',
  gender: 'Male',
  id: '112',
  jobTitle: 'JavaScript Developer',
  lastName: 'Employee',
  linkedIn: null,
  location: 'Remote',
  mobilePhone: null,
  photoUploaded: false,
  photoUrl:
    'https://spaceagencyupwork.bamboohr.com/images/photo_placeholder.gif',
  preferredName: 'T-one',
  workEmail: '2110pro@mail.ru',
  workPhone: '+71231231212',
  workPhoneExtension: null,
};
