export enum GoogleOperationName {
  AUTH_FLOW_START = 'GOOGLE/AUTH_FLOW/START',
  AUTH_FLOW_COMPLETE = 'GOOGLE/AUTH_FLOW/COMPLETE',
  AUTH_FLOW_REFRESH = 'GOOGLE/AUTH_FLOW/REFRESH',
  PEOPLE_SEARCH = 'GOOGLE/PEOPLE/SEARCH'
}
