export enum GoogleOperationName {
  AUTH_FLOW_START = 'GOOGLE/AUTH_FLOW/START',
  AUTH_FLOW_COMPLETE = 'GOOGLE/AUTH_FLOW/COMPLETE',
  PEOPLE_SEARCH = 'GOOGLE/PEOPLE/SEARCH',
  PEOPLE_CREATE = 'GOOGLE/PEOPLE/CREATE',
  PEOPLE_UPDATE = 'GOOGLE/PEOPLE/UPDATE',
  PEOPLE_DELETE = 'GOOGLE/PEOPLE/DELETE'
}
