export enum BreadOperationName {
  SETUP_BASIC_AUTH = 'BREAD/SETUP_BASIC_AUTH',
  EMPLOYEE_SEARCH = 'BREAD/EMPLOYEE/SEARCH',
  EMPLOYEE_CREATE = 'BREAD/EMPLOYEE/CREATE',
  EMPLOYEE_UPDATE = 'BREAD/EMPLOYEE/UPDATE'
}
