export const BREAD_COMMAND_NAME_LIST = [
  'EMPLOYEE_BY_ID',
  'EMPLOYEE_SEARCH',
  'EMPLOYEE_CREATE',
  'AUTH_BASIC_SAVE',
  'AUTH_OAUTH2_START',
  'AUTH_OAUTH2_COMPLETE',
  'AUTH_OIDC_START',
  'AUTH_OIDC_COMPLETE',
] as const;
