import { enumPrefixed } from '@easybread/common';

const BREAD_BASIC_COMMAND_LIST = [
  'BASIC_USER_SEARCH',
  'BASIC_USER_BY_ID',
  'BASIC_USER_CREATE',
  'BASIC_USER_UPDATE',
  'BASIC_USER_DELETE',
] as const;

const BREAD_AUTH_COMMAND_NAME_LIST = [
  'AUTH_OIDC_COMPLETE',
  'AUTH_BASIC_SET',
  'AUTH_OAUTH2_START',
  'AUTH_OAUTH2_COMPLETE',
  'AUTH_OIDC_START',
] as const;

const BREAD_HR_COMMAND_NAME_LIST = [
  'HR_ORGANIZATION_SEARCH',
  'HR_JOB_POSTING_SEARCH',
  'HR_JOB_APPLICATION_SEARCH',
  'HR_JOB_APPLICANT_SEARCH',
  'HR_EMPLOYEE_SEARCH',
  'HR_EMPLOYEE_BY_ID',
  'HR_EMPLOYEE_CREATE',
  'HR_EMPLOYEE_UPDATE',
] as const;

export const BREAD_COMMAND_NAME = enumPrefixed('BREAD' as const, [
  ...BREAD_BASIC_COMMAND_LIST,
  ...BREAD_AUTH_COMMAND_NAME_LIST,
  ...BREAD_HR_COMMAND_NAME_LIST,
]);
