name: ci-release

on:
  push:
    tags:
      - v*.*.*

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      # Connect your workspace by running "nx connect" and uncomment this
      # - run: pnpm dlx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          registry-url: https://registry.npmjs.org/

      - run: pnpm install --frozen-lockfile

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: pnpm exec nx-cloud record -- echo Hello World

      - name: Print Environment Info
        run: pnpm nx report
        shell: bash

      - name: Print Version
        run: |
          echo "Version: ${{ github.ref_name }}"

      # For some reason, `nx release publish` doesn't build the packages (`nx release` does)
      # even if we set `"dependsOn": [ "build" ]` in the nx.json file for the `nx-release-publish` target.
      # So we build manually
      - name: Build packages
        run: pnpm nx run-many -t test,build --exclude="playground*"
        shell: bash

      - name: Publish packages
        id: publish
        run: pnpm nx release publish --access public --registry=https://registry.npmjs.org/
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          NPM_CONFIG_PROVENANCE: true

      - name: Notify Success to Discord
        uses: sarisia/actions-status-discord@v1.14.6
        if: ${{ steps.publish.outcome == 'success' }}
        with:
          webhook: ${{ secrets.DISCORD_ACTIONS_WEBHOOK }}
          status: ${{ job.status }}
          title: "Release - ${{ github.workflow }}"
          description: "Tag: ${{ github.ref }} - Commit: ${{ github.sha }}"
          content: "Release Job successful!"
          color: 0x25e565

      - name: Notify Failure to Discord
        uses: sarisia/actions-status-discord@v1.14.6
        if: ${{ job.status == 'failure' }}
        with:
          webhook: ${{ secrets.DISCORD_ACTIONS_WEBHOOK }}
          status: ${{ job.status }}
          title: "Release - ${{ github.workflow }}"
          description: "Tag: ${{ github.ref }} - Commit: ${{ github.sha }}"
          content: "Release Job Failed!"
          color: 0xEF4650
